Twap last min order issue fix
bitfinexcom/bfx-hf-algo pull request #176
Opened 2021-07-12 11:39 UTC by avsek477

Issue: The last order generated may be less than the minimum order size because of the remaining amount, hence, causing it to stop the  algo order.

This PR provides fix to this issue.

2021-07-12 13:25 UTC, robertkowalski commented on lib/twap/meta/get_ui_def.js
> +    '\n\nNote: If amount distortion is provided, the total sliced order amounts will',
`the total order amounts will`

2021-07-12 13:26 UTC, robertkowalski requested changes
small text issue

also last order fails for me with: invalid order size: minimum amount required -- is that expected?

2021-07-13 03:24 UTC, avsek477 commented on lib/twap/meta/get_ui_def.js
> +    '\n\nNote: If amount distortion is provided, the total sliced order amounts will',
fixed

2021-07-15 07:21 UTC, robertkowalski commented
lgtm

2021-07-15 07:21 UTC, merged