use packetWDDelay from user setting
bitfinexcom/bfx-hf-algo pull request #224
Opened 2023-02-27 16:45 UTC by arifjmamun

2023-02-28 07:02 UTC, avsek477 requested changes

2023-02-28 07:02 UTC, avsek477 commented on lib/ws_adapter.js
> +      packetWDDelay
Please add a default value as well. You can use 30 seconds as default.

2023-02-28 09:36 UTC, avsek477 approved these changes

2023-03-01 11:48 UTC, tarcisiozf approved these changes

2023-03-01 14:34 UTC, merged