[WIP] Fix: algos calcs float issues
bitfinexcom/bfx-hf-algo pull request #44
Opened 2020-12-01 17:26 UTC by alexstotsky

### PR description
- Fixed floating point issues in TWAP, Ping/Pong and Accumulate/Distribute algo orders calcs
- Task description https://app.asana.com/0/1125859137800433/1199204485116691

2020-12-03 17:07 UTC, robertkowalski commented on test/lib/twap/events/orders_order_fill.js
> +              remainingAmount: 0.3
> 0.5 - 0.2
0.3
> 0.5 - 0.3
0.2

2020-12-03 17:08 UTC, robertkowalski commented on test/lib/twap/events/orders_order_fill.js
> +              remainingAmount: 0.3
try 0.3 - 0.2

2020-12-03 17:09 UTC, robertkowalski commented on test/lib/twap/util/is_target_met.js
> +    assert.ok(isTargetMet({ priceTarget: 0.5, priceDelta: 0.2 }, 0.7))
not all floats run into this issue:

```
> 0.5 - 0.2
0.3
> 0.5 - 0.3
0.2
> 0.3 - 0.1
0.19999999999999998
> 0.3 - 0.2
0.09999999999999998
```

2020-12-03 17:11 UTC, robertkowalski commented on test/lib/accumulate_distribute/events/orders_order_fill.js
> +              remainingAmount: 0.5
did this run into odd values before the fix (see other comments)

2020-12-03 17:16 UTC, robertkowalski commented on lib/ping_pong/util/gen_ping_pong_table.js
> +    const step = (nBN(pingMaxPrice).minus(pingMinPrice).toNumber()) / (orderCount - 1)
> 1.2 / 3
0.39999999999999997

2020-12-03 17:17 UTC, robertkowalski commented on lib/ping_pong/util/gen_ping_pong_table.js
> +    const step = (nBN(pingMaxPrice).minus(pingMinPrice).toNumber()) / (orderCount - 1)
not fully fixed here

2020-12-07 17:57 UTC, robertkowalski commented on test/lib/accumulate_distribute/events/orders_order_fill.js
> +      stateParams: {remainingAmount: 0}
```
  /Users/robert/bitfinex/bfx-hf-algo/test/lib/accumulate_distribute/events/orders_order_fill.js:42:20: A space is required after '{'.
  /Users/robert/bitfinex/bfx-hf-algo/test/lib/accumulate_distribute/events/orders_order_fill.js:42:39: A space is required before '}'.
  /Users/robert/bitfinex/bfx-hf-algo/test/lib/accumulate_distribute/events/orders_order_fill.js:63:26: Unexpected trailing comma.
```

2020-12-07 18:12 UTC, robertkowalski commented on test/lib/accumulate_distribute/meta/init_state.js
> +    const stubOrderAmountsGen = sinon.stub(orderAmounts, 'gen').returns([0.001, 0.002])
if `gen.orderAmounts` is stubbed, what float function are we testing here then?

might be missing something, but i think we can delete this test

2020-12-07 18:13 UTC, robertkowalski commented on lib/accumulate_distribute/meta/init_state.js
> +  if (Math.abs(nBN(totalAmount).minus(amount).toNumber()) > DUST) {
total amount is just used internally, for a check on dust, no need for that. 

(you can revert this file back)

2020-12-07 18:15 UTC, robertkowalski commented on lib/accumulate_distribute/util/gen_order_amounts.js
> +      totalAmount = nBN(totalAmount).plus(cappedOrderAmount).toNumber()
ok, something is wrong here. if i revert all changes here in the file and run the testsuite, tests still pass for me.

2020-12-07 18:18 UTC, robertkowalski commented on lib/accumulate_distribute/util/generate_order.js
> +const { nBN } = require('@bitfinex/lib-js-util-math')
this is part the core functionality of the algo. 

would be good to have two tests: one that ensures that we did not break anything and another that verifies the float handling that we added.

2020-12-07 18:21 UTC, robertkowalski requested changes
i started with an in-depth review of accumulate-distribute, sadly too many issue found to continue with other algos without making this a very long standing PR where its easy to lose track of important changes and requirements.

suggestion: please open a new PR, just for the corrected accumulate-distribute part. then we get accumulate-distribute ready for shipping and focus on the next algo with another new PR

2020-12-08 11:48 UTC, alexstotsky commented
ok, will divide into several PRs, one per strategy

2020-12-08 11:49 UTC, closed without merging